on:
  push:
    branches:
      - master

env:
  ResourceGroup: letsencrypt
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # pin@v2
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI ARM deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          cd internal/deploy
          chmod +x deploy.sh
          ./deploy.sh $ResourceGroup
